const express = require("express");
const router = express.Router();
const { verifyToken } = require("../middlewares/Verify");
const { LoginController, RegisterController, RefreshTokenController, GoogleSignUpIN, PasswordRecovery, ResetPassword, } = require("../controllers/Register-Login/AuthController");
const { UserDashBoardLoggedUser, UserDashBoardUnLoggedUser, showSuscriberlist, showpurchasedplan, ShowDescription, } = require("../controllers/User Operations/UserDashboard");
const { Suscribe, Unsubscribe, buyPlan, } = require("../controllers/User Operations/UserOperations");
router.post("/login", LoginController);
router.post("/register", RegisterController);
router.post("/refresh", RefreshTokenController);
router.post("/google/login", GoogleSignUpIN);
router.post("/password-recovery", PasswordRecovery);
router.post("/reset-password", verifyToken, ResetPassword);
router.get("/dashboard/public", UserDashBoardUnLoggedUser);
router.get("/dashboard/user", verifyToken, UserDashBoardLoggedUser);
router.get("/dashboard/subscribers", verifyToken, showSuscriberlist);
router.get("/dashboard/purchased", verifyToken, showpurchasedplan);
router.get("/dashboard/description/:uuid", verifyToken, ShowDescription);
router.post("/subscribe", verifyToken, Suscribe);
router.post("/unsubscribe", verifyToken, Unsubscribe);
router.post("/buy-plan", verifyToken, buyPlan);
module.exports = router;
