const express = require("express");
const router = express.Router();
const { LoginController, RegisterController, RefreshTokenController, GoogleSignUpIN, PasswordRecovery, ResetPassword, } = require("../controllers/Register-Login/AuthController");
const { UserDashBoardLoggedUser, UserDashBoardUnLoggedUser, showSuscriberlist, showpurchasedplan, ShowDescription, } = require("../controllers/User Operations/UserDashboard");
const { Suscribe, Unsubscribe, buyPlan, } = require("../controllers/User Operations/UserOperations");
router.post("/login", LoginController);
router.post("/register", RegisterController);
router.post("/refresh", RefreshTokenController);
router.post("/google/login", GoogleSignUpIN);
router.post("/password-recovery", PasswordRecovery);
router.post("/reset-password", ResetPassword);
router.get("/dashboard/public", UserDashBoardUnLoggedUser);
router.get("/dashboard/user", UserDashBoardLoggedUser);
router.get("/dashboard/subscribers", showSuscriberlist);
router.get("/dashboard/purchased", showpurchasedplan);
router.get("/dashboard/description/:uuid", ShowDescription);
router.post("/subscribe", Suscribe);
router.post("/unsubscribe", Unsubscribe);
router.post("/buy-plan", buyPlan);
module.exports = router;
